#!/usr/bin/bash

#SBATCH -A adaptree
#SBATCH -p normal_q
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4
#SBATCH -t 36:00:00
####### end of job customization

cd /work/amsand/admixture_filtered_dentata

/home/amsand/bin/Plink/plink \
        --vcf /work/amsand/VCF/American_chestnut_356_snps_only_filtered_remove_fail_miss_0.9_maf_0.002.vcf.gz \
        --const-fid 0 \
        --set-missing-var-ids @:#[Cd]\$1,\$2 \
	--allow-extra-chr \
        --autosome \
        --make-bed

wait

/home/amsand/bin/Plink/plink --bfile plink --indep-pairwise 50 10 0.1

wait

/home/amsand/bin/Plink/plink --bfile plink --extract plink.prune.in --make-bed --out prunedData

##The pruneData output files were then converted to a vcf file using plink for input into R for DAPC analysis.

$HOME/bin/plink2 --bfile /work/C_dentata_WGS/dentata_356_prunted/plink_files/prunedData --ref-from-fa /home/amsand/chestnut_genome/Castanea_dentata.mainGenome.fasta --recode vcf id-paste=iid --out dentata_356_pruned

#Name of vcf file: dentata_356_pruned.vcf.gz