#!/usr/bin/bash

#SBATCH -A adaptree
#SBATCH -p dev_q
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4
#SBATCH -t 2:00:00
####### end of job customization

cd $WORK/Pure_American_Analysis/VCFs

$HOME/bin/bcftools stats \
	-F /work/cascades/amsand/ChestnutPureGenome/Castanea_dentata.mainGenome.fasta \
	-s - subsample_384_100k.vcf
[amsand@calogin1 VCFs]$ cat vcftools_quality_check.sh 
#!/usr/bin/bash

#Scripts from https://speciationgenomics.github.io/filtering_vcfs/

# move to your vcf directory
#cd ~/vcf
# copy the data file from the data directory
#cp /home/data/vcf/cichlid_full.vcf.gz* ./

#Check number of variants
#bcftools view -H cichlid_full.vcf.gz | wc -l

#VCF file subsetting
#bcftools view cichlid_full.vcf.gz | vcfrandomsample -r 0.012 > cichlid_subset.vcf

#make directory for results
#mkdir /work/cascades/amsand/Pure_American_Analysis/VCFs/vcftools

#Declare variables
SUBSET_VCF=/work/cascades/amsand/Pure_American_Analysis/VCFs/American_chestnut_WGS_384_samples_filtered_remove_fail_miss_0.9.vcf.recode.vcf.gz
OUT=/work/cascades/amsand/Pure_American_Analysis/VCFs/vcftools/American_chestnut_384_quality_check

#Calculate allele frequency
#vcftools --gzvcf $SUBSET_VCF --freq2 --out $OUT --max-alleles 2

#Calculate mean depth of coverage per individual
vcftools --gzvcf $SUBSET_VCF --depth --out $OUT

#Calculate mean depth per site
vcftools --gzvcf $SUBSET_VCF --site-mean-depth --out $OUT

#Calculate site quality
vcftools --gzvcf $SUBSET_VCF --site-quality --out $OUT

#Calculate proportion of missing data per individual
vcftools --gzvcf $SUBSET_VCF --missing-indv --out $OUT

#Calculate proportion of missing data per site
vcftools --gzvcf $SUBSET_VCF --missing-site --out $OUT

#Calculate heterozygosity and inbreeding coefficient per individual
vcftools --gzvcf $SUBSET_VCF --het --out $OUT

##End of stats, now send files to R for final analysis and visualization.
##VCF files was checked for quality and samples with greater than 10% missing data were removed