#!/bin/bash

input=$1

##align short reads via bwa mem
cd $WORK/Pure_American_WGS_Samples
sample=$(basename ${input/_R1.fastq/})
#Normally, don't have to use this other sample name, but because I merged BAM files from different lanes of same file, they must have the same SM label.
sampleRGSM=$(basename ${input/_I9*.fastq/})
outdir="$WORK/Pure_American_Analysis/SAMs2/$sample.sam" #make sure you have SAMs created. mkdir SAMs

/work/newriver/amsand/GenomeAnalysis/bin/bwa-0.7.15/bwa mem -M -R "@RG\tID:Sample_$sample\tSM:$sampleRGSM" -t 5 /work/newriver/amsand/ChestnutPureGenome/Castanea_dentata.mainGenome.fasta \
        $WORK/Pure_American_WGS_Samples/"$sample"_R1.fastq $WORK/Pure_American_WGS_Samples/"$sample"_R2.fastq > $outdir #R flag is really important! not sure if you are using it...


##Convert SAM to BAM (Sorted and Indexed)
#cd /work/newriver/amsand/GenomeAnalysis/SAMs
outdir1="$WORK/Pure_American_Analysis/BAMs/$sample"
outdir2="$WORK/Pure_American_Analysis/BAMs/$sample.bam" #make sure you have "BAMs" created. mkdir BAMs
/work/newriver/amsand/GenomeAnalysis/bin/samtools view -bS $outdir | /work/newriver/amsand/GenomeAnalysis/bin/samtools sort -m 3G -o $outdir2 -@ 5 && /work/newriver/amsand/GenomeAnalysis/bin/samtools index $outdir2
