#!/usr/bin/bash
###Couldn't get this to work
bwatosam() {
  id="$1"

  /work/newriver/amsand/GenomeAnalysis/bin/bwa-0.7.15/bwa mem -t 5 -M -R "@RG\tID:{}\tSM:{}\tPL:ILLUMINA\tLB:{}" /work/newriver/amsand/ChestnutPureGenome/Castanea_dentata.mainGenome.fasta "$id"_R1.fastq "$id"_R2.fastq |
    /work/newriver/amsand/Pure_American_Analysis/bin/samtools view -Sbo /work/newriver/amsand/Pure_American_Analysis/SAMs2/"$id".bam
}
export -f bwatosam

# --plus enables {%...} to remove a substring    
ls *_R1.fastq |
  parallel --plus bwatosam {%_R1.fq.gz}
