#!/usr/bin/bash

#SBATCH -J hello-world
#SBATCH -p normal_q

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=2:00:00
#SBATCH --mem-per-cpu=24G

#SBATCH --account=introtogds
#SBATCH --export=NONE

echo "hello world"

cd $WORK/DNA_Practice/Practice/data

mkdir $WORK/DNA_Practice/Practice/results/bam

for f in *.sam; do #Designates what file extension to look for
    $WORK/DNA_Practice/Practice/bin/samtools-1.9/samtools view -S -bh "$f" > $WORK/DNA_Practice/Practice/results/bam/"${f%.sam}.bam"
 
done
#ls *.sam | xargs -n 1 -I {} sh -c 'samtools view -S -bh {} > {}.bam'
#ls *.sam | parallel 'samtools view -S -bh {} > {.}.bam'
#This converts the .sam files into a bam file for more easy analysis.

#Then you need to sort the BAM files before your can index them.>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
cd $WORK/DNA_Practice/Practice/results/bam

for f in *.bam; do #Designates what file extension to look for
    $WORK/DNA_Practice/Practice/bin/samtools-1.9/samtools sort "$f" -o > $WORK/DNA_Practice/Practice/results/bam_sorted/"${f%.bam}_sorted.bam"
    #Usually should write sort in.file -o out.file>>>but i already have the input file as a bam file so not needed. -o just designates the output file to be a bam file.
 
done
###Then Index the files >>>>>>>>>>>>>>>>>>>>>>>>>>>

#!/usr/bin/bash

#SBATCH -J hello-world
#SBATCH -p normal_q

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=5:00:00
#SBATCH --mem-per-cpu=24G

#SBATCH --account=introtogds
#SBATCH --export=NONE

echo "hello-world"

cd $WORK/DNA_Practice/Practice/results/bam_sorted

for f in *_sorted.bam; do
$WORK/DNA_Practice/Practice/bin/samtools-1.9/samtools index "$f" > $WORK/DNA_Practice/Practice/results/bam_sorted/"${f%_sorted.bam}_sortedIndex.bam"

done


